export enum StepEnum {
  ABOUT = 'ABOUT',
  FINAL_STATE_CHOICE = 'FINAL_STATE_CHOICE',
  START_STATE_CHOICE = 'START_STATE_CHOICE',
  ALGORITHM_CHOISE = 'ALGORITHM_CHOISE',
  SOLVING = 'SOLVING',
  SOLVED = 'SOLVED',
}